# runa.toml - default configuration for runa

# Note:
# Commented values are the internal defaults of runa
# Use hex codes (eg. "#RRGGBB") or terminal colors ("cyan")
# To get configuration help, check out the runa documentation.

# General behavior
[general]
dirs_first = true
show_hidden = true
# show_symlink = true
# show_system = false
# case_insensitive = true
# always_show = []
# max_find_results = 2000
# move_to_trash = true

[display]
# selection_marker = false
# dir_marker = true
borders = "unified"
# border_shape = "square"
# titles = true
icons = false
# separators = true
parent = true
preview = true
# preview_underline = true
# preview_underline_color = false
# entry_padding = 1
# scroll_padding = 5
# toggle_marker_jump = false
# instant_preview = true

# [display.preview_options]
# method = "internal"
# bat related options if method = "bat"
# theme = "default"
# style = "plain"
# wrap = false
# tab_width = 4

# [display.layout]
# parent = 20
# main = 40
# preview = 40

# [display.info]
# name = true
# file_type = false
# perms = false
# size = true
# modified = true
# created = true
# accessed = false
# position = "bottom_left"
# status_bar = true
# format = "{perms} | {size}"
# date_format = "%Y-%m-%d %H:%M"

# [display.status]
# entry_count = "footer"
# filter = "header"
# markers = "footer"
# clipboard = "footer"
# tasks = "footer"
# tabs = "header"

[theme]
name = "default"
# selection_icon = ""
# exe_color = "default"

# [theme.selection]
# fg = "default"
# bg = "default"

# [theme.accent]
# fg = "default"
# bg = "default"

# [theme.entry]
# fg = "default"
# bg = "default"

# [theme.directory]
# fg = "default"
# bg = "default"

# [theme.separator]
# fg = "default"
# bg = "default"

# [theme.parent]
# fg = "default"
# bg = "default"
# selection_mode = "on"
# selection.fg = "default"
# selection.bg = "default"

# [theme.preview]
# fg = "default"
# bg = "default"
# selection_mode = "on"
# selection.fg = "default"
# selection.bg = "default"

# [theme.underline]
# fg = "default"
# bg = "default"

# [theme.path]
# fg = "default"
# bg = "default"

# [theme.symlink]
# directory = "default"
# file = "default"
# target = "default"

# [theme.marker]
# icon = "*"
# fg = "default"
# bg = "default"
# clipboard.fg = "default"
# clipboard.bg = "default"

# [theme.widget]
# color.fg = "default"
# color.bg = "default"
# label.fg = "blue"
# label.bg = "default"
# value.fg = "cyan"
# value.bg = "default"
# border.fg = "default"
# border.bg = "default"
# size = "medium"           # "small", "medium", "large" or [w ,h] or { w = 30, y = 30 }.
# position = "center"       # "center", "top_left", "bottomright", or [x, y] (percent) or { x = 42, y = 80 }.
# confirm_size = "large"
# move_size = [70, 14]
# find_visible_results = 5
# find_width = 40
# goto_help.size = [58, 3]
# goto_help.position = "bottom"

# [theme.status_line]
# fg = "default"
# bg = "default"

# [theme.tab]
# marker = ""
# separator = ":"
# active.fg = "yellow"
# active.bg = "default"
# inactive.fg = "gray"
# inactive.bg = "default"
# line_format = "[{idx}]"

# [theme.info]
# perms.fg = "lightgreen"
# perms.bg = "default"
# size.fg = "default"
# size.bg = "default"
# date.fg = "default"
# date.bg = "default"
# modified.fg = "default"
# modified.bg = "default"
# created.fg = "default"
# created.bg = "default"
# accessed.fg = "default"
# accessed.bg = "default"
# file_type.fg = "default"
# file_type.bg = "default"
# owner.fg = "default"
# owner.bg = "default"
# group.fg = "default"
# group.bg = "default"

# [editor]
# cmd = "nvim"

# [keys]
# open_file = ["enter"]
# go_up = ["k", "up"]
# go_down = ["j", "down"]
# go_parent = ["h", "left", "back"]
# go_into_dir = ["l", "right"]
# quit = ["q", "esc"]
# delete = ["d"]
# copy = ["y"]
# paste = ["p"]
# rename = ["r"]
# create = ["n"]
# create_directory = ["N"]
# move_file = ["m"]
# filter = ["f"]
# toggle_marker = ["space"]
# info = ["i"]
# find = ["s"]
# clear_markers = ["<c-c>"]
# clear_filter = ["<c-f>"]
# clear_clipboard = ["<f2>"]
# clear_all = ["<c-l>"]
# select_all = ["<c-a>"]
# alternate_delete = ["<m-d>"]
# go_to_bottom = ["G"]
# keybind_help = ["?"]

# Keys triggered by pressing "g" once
# go_to_top = ["g"]
# go_to_home = ["h"]
# go_to_path = ["p"]

# Tab actions
# tab_new = ["<c-t>"]
# tab_close = ["<c-w>"]
# tab_cycle = ["<c-n>"]
# tab_next = ["<c-n>"]
# tab_prev = ["<c-p>"]

# Widget scroll
# scroll_up = ["<c-d>"]
# scroll_down = ["<c-u>"]
