[book]
title = "Runa Configuration Guide"
authors = ["Alexandros McCray <alexandros@amccray.com>"]
language = "en"
src = "config"

[output.html]
git-repository-url = "https://github.com/alexm-dev/runa"
