name: Update Issue Template Versions
on:
  push:
    branches: [main]
    paths: ['Cargo.toml']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Versions
        id: vars
        run: |
          CARGO_V=$(grep -m 1 '^version =' Cargo.toml | cut -d '"' -f 2)
          STABLE_V=$(git describe --tags --abbrev=0 2>/dev/null || echo "None")
          echo "cargo=$CARGO_V" >> $GITHUB_OUTPUT
          echo "stable=$STABLE_V" >> $GITHUB_OUTPUT

      - name: Update YAML template
        run: |
          yq -i '(.body[] | select(.id == "version") | .attributes.options) = ["Latest Release ('${{ steps.vars.outputs.stable }}')", "Development ('${{ steps.vars.outputs.cargo }}')", "Other / Git Commit Hash"]' .github/ISSUE_TEMPLATE/bug_report.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync issue template versions [skip ci]"
